public without sharing class Constants {
  
    public static final String materialObjAPIName = 'Product2';
    public static final String materialNewPrrodRTName = 'New Products';
    public static final String noPlant = 'No Plant';
    public static final String queue = 'Queue';
    public static final String ecophon = 'Ecophon';
    public static final String meridianPlantCode = '0813';
    public static final String bigBoardPlantCode = '0815';
   
}