public class ContactTriggerHandler1 {
    public static void UpdatePhoneAccount(List<contact> lstobjcon){
        //  set<id> setconid = new set<id>();
       /* list<contact> lstacc =[select id,phone From contact where phone != null];
        for(contact con : lstobjcon) {
            for(contact con1 : lstacc){
                if(con.Phone == con1.phone){
                    con.Phone.adderror('the phone is already exist');
                }else if(con.Phone == null){
                    con.Phone.adderror('enter the phone');
                }
            }        
            //map<id,contact> oldmap = new map<id,contact>(select id ,Phone FROM contact where phone != null);
            
        } */
    } 
}