public class insertthroughlist {
  list<Account> lstacc = new list<Account>();  
      public void insertrecord(string name){
            list<Account> lstacc = new list<Account>(); 
          Account acc = new Account(); 
          acc.Name = name;
          acc.AccountNumber = '54343';
          lstacc.add(acc);
              insert lstacc;
      }          
          
          
          
      
}