public with sharing class PAPResponse {
public String EffDate {get; set;}
        public String Plant {get; set;}
        public String SalesOrg {get; set;}
        public String District {get; set;}
        public String ItemClass {get; set;}
        public String Material {get; set;}
        public String Idc {get; set;}
        public Decimal UnitAreaPrice {get; set;}
        public String UnitCurrency {get; set;}
        public String UnitPriceUom {get; set;}
        public Decimal SapSelPrice {get; set;}
        public String SapSelCurr {get; set;}
        public String SapSelUom {get; set;}
}