public with sharing class PAPRequest {
 
  public string plant {get;set;}
  public string org {get;set;}
   public string ivdate {get;set;}
     public string district {get;set;}
        public string ividc {get;set;}
                public string material {get;set;}
                   // public tempuriOrg.ArrayOfZtsdPriceArea input {get; set;}
                              
                               public string division1{get;set;}
}