@isTest
public class prodsapComPricingTest{
    static testmethod void testmethodprodsapComPricing(){
        prodsapComPricing pcp = new prodsapComPricing();
        prodsapComPricing.ArrayOfZTSD_PRICE_AREA_O  apa = new prodsapComPricing.ArrayOfZTSD_PRICE_AREA_O();
        apa.item = null;
        prodsapComPricing.ZSdWsdlPriceAreaPriceFmResponse pam = new prodsapComPricing.ZSdWsdlPriceAreaPriceFmResponse();
        pam.GtOutput = null;
    }
}