//Run the test methods for each class, this is a workaround to get code coverage due to time constraints
@IsTest 
public class TestCode{
    public static testMethod void runTest() {
        //START Commented by Kritika Bhati for S-503814
        
         //LargeJobQuote.testCoverage(); // Commented by Kritika Bhati for S-509747
        //ApprovalProcessAction.testCoverage();
        //ljqNewProduct.testCoverage();// Commented by Kritika Bhati for S-509747
        // NewPCREntryController.testCoverage();// Commented by Kritika Bhati for S-509747
        //UtilityClass.testCoverage();
        //PriceChangeRequestListController.testCoverage();
        //LargeJobQuoteList.testCoverage();
        //ljqProductEscalator.testCoverage();
        //LJQEmailController.testCoverage();
        //Constants.testCoverage();
        //CustomApprovalProcessController.testCoverage();
        //PATRebateCloneWithItemsController.testCoverage();
        //QuoteCustomApprovalProcessController.testCoverage();
        //PCRApprovalEmailTemplateProcess.testCoverage();

        //END S-503814
    }
}