/**********************************************************************
Name:  WOD_IntegrationExceptionTest
===============================================================
Purpose: Test data set up class                                                                                                               
===============================================================
===============================================================
History                                                            
-------                                                            
  AUTHOR        DATE            DETAIL                        
  Tavant     02/06/2021      INITIAL DEVELOPMENT            
***********************************************************************/
@isTest
public class WOD_IntegrationExceptionTest {
	public static testmethod void integrationExceptionMethod(){
        WOD_IntegrationException ex = new WOD_IntegrationException();
        //ex.emtyMethod();
        //ex.msg ='test';		        
    }
}